[package]
name = "verandah-plugin-utils"
version = "0.7.0"
edition = "2024"
description = "Common utilities for verandah widget plugins"
license = "MIT"
repository = "https://github.com/sw1nn/verandah-plugin-utils"

[dependencies]
verandah-image = { path = "../verandah-image" }

# Serde
serde = "1"

[dev-dependencies]
